
[cursor]
    unfocused_hollow = true

[cursor.style]
    shape = "Block"

[env]
    TERM = "alacritty"

[mouse]
    hide_when_typing = false

[scrolling]
    history = 50000
    multiplier = 3

[selection]
    save_to_clipboard = false
    semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[terminal.shell]
    args = ["-l", "-c", "/opt/homebrew/bin/tmux -u new-session -D -A -s main"]
    program = "/bin/zsh"

[window]
    decorations = "full"
    dynamic_padding = false
    dynamic_title = true
    opacity = 1.0
    option_as_alt = "Both"
    startup_mode = "Windowed"

    [window.dimensions]
        columns = 0
        lines = 0

    [window.padding]
        x = 0
        y = 0

    [window.position]
        x = 0
        y = 0

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/styling.toml",
    "~/.config/alacritty/bindings.generic.toml",
    "~/.config/alacritty/bindings.macos.toml"
]

[terminal]
